### ISSUE TITLE
Vesting rate seems broken

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1393]
For [this](https://github.com/zerocracy/farm/issues/860) issue, I got paid ``$8``, which is the correct amount of cash (30min from the cash rate of ``$16``), but I got ``$8`` of shares as well, when it should have been ``$16`` (my vesting rate, according to the zerocracy UI is ``$32``).

I noticed it in another ticket as well, it seems that 0crat gives shares in value of the remaining cash up to 1h. In that case, I got ``$4`` cash (15min ``REV`` job) + ``$12`` vesting.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil there was a bug in equity calculation https://github.com/zerocracy/farm/issues/1281, but now it should be fixed, please see http://www.zerocracy.com/policy.html#37. If your vesting rate is `$32` and cash rate is `$16`, you should always receive same amount of shares and cash for each task: `cash = $16 * 30 min / 60 min`, `shares = ($32 - $16) * 30 min / 60 min`

**Comment by amihaiemil** [comment]
@g4s8 Oh, I see. Then the UI should be changed a little maybe? It should be ``Hourly rate: $32 ($16 cash and $16 vesting)``. Right now, I thought that my full rate was $48 ($16 cash + $32 vesting) -- what do you think?

**Comment by amihaiemil** [comment]
@g4s8 

> now it should be fixed, 

I will keep an eye open for future payments and let you know if I notice it again

**Comment by amihaiemil** [comment]
@g4s8 For [this](https://github.com/zerocracy/farm/pull/1376) task I got ``$4`` cash (15min of ``$16`` hourly rate, which is correct) and ``$12`` shares. So it is still not as you said above, maybe the bug fix is not released yet?

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1393#issuecomment-403876469))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1393](https://github.com/zerocracy/farm/issues/1393) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231393%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@amihaiemil you're right, westing rate calculation is broken, it depends on `minutes` parameter but it should not:
```groovy
Cash reward = (vesting.rate(login).mul(minutes) / 60).add(cash.mul(-1L))
```

**Comment by 0crat** [comment]
Job [#1393](https://github.com/zerocracy/farm/issues/1393) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@amihaiemil it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1393` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1393](https://github.com/zerocracy/farm/issues/1393) is now out of scope
