### ISSUE TITLE
Previously refused job was reassigned

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1396]
Issue #733 was previously assigned to me by `0crat`. I [refused](https://github.com/zerocracy/farm/issues/733#issuecomment-400138821) this task because I couldn't reproduce it. A few days later it was then [reassigned](https://github.com/zerocracy/farm/issues/733#issuecomment-403471284) to me.

![image](https://user-images.githubusercontent.com/1917892/42481713-6ebe4202-8416-11e8-926c-db7666876c8d.png)

Querying `@0crat` for [status](https://github.com/zerocracy/farm/issues/733#issuecomment-403652726) showed that there were no bans for the task, despite the fact that [literally](https://github.com/zerocracy/farm/issues/733#issuecomment-384889324) [everyone](https://github.com/zerocracy/farm/issues/733#issuecomment-390757484) [else](https://github.com/zerocracy/farm/issues/733#issuecomment-394099434) refused (maybe for the same reason I did ;) ) and should have shown up in the bans list as having resigned from the ticket.

![image](https://user-images.githubusercontent.com/1917892/42481696-64563716-8416-11e8-8555-81f5cf7f76b1.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@carlosmiranda it's strange: you was banned without errors, but now I can't see this job in `bans.xml`:
```
1770040144 14days "User was banned" (0.23.2)
  issue: 733
  repo: zerocracy/farm
  voluntarily: true
  login: carlosmiranda
  token: github;zerocracy/farm;733;400138777
  comment: 400138777
  job: gh:zerocracy/farm#733
  flow: Cancel order; Order was canceled

1770040142 14days "Order was canceled" (0.23.2)
  issue: 733
  repo: zerocracy/farm
  voluntarily: true
  login: carlosmiranda
  token: github;zerocracy/farm;733;400138777
  comment: 400138777
  job: gh:zerocracy/farm#733
  flow: Cancel order

1770040140 14days "Cancel order" (0.23.2)
  issue: 733
  author: carlosmiranda
  repo: zerocracy/farm
  token: github;zerocracy/farm;733;400138777
  comment: 400138777
  job: gh:zerocracy/farm#733
```

**Comment by 0crat** [comment]
Job [#1396](https://github.com/zerocracy/farm/issues/1396) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by olenagerasimova** [comment]
@carlosmiranda @g4s8 I've just got same problem with one [issue from harvest](https://github.com/harvest-foundation/telegram/issues/169)
![image](https://user-images.githubusercontent.com/14931449/44536660-a2a1fc00-a705-11e8-8af7-d1c24741b1c8.png)
according to 0crat I'm not banned from the job 
![image](https://user-images.githubusercontent.com/14931449/44536761-d846e500-a705-11e8-80ac-b5caffc50227.png)

**Comment by paulodamaso** [comment]
@carlosmiranda @g4s8  0crat returned me all recently refused jobs (#1533, #1347, sunsofterp/portal#128) and even some ones that were stuck in REV status for some long time ago (yegor256/takes#836). Then, I've refused yegor256/takes#836 in 28/08/2018 for the second time, but 0crat insisted and assigned it to me again in 31/08/2018, see yegor256/takes#836 (comment)

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/zerocracy/farm/issues/1396#issuecomment-417946631))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1396](https://github.com/zerocracy/farm/issues/1396), see [§21](http://www.zerocracy.com/policy.html#21); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1396#issuecomment-418532694))

@paulodamaso This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1396](https://github.com/zerocracy/farm/issues/1396) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231396%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 Looks like something is resetting the bans and clearing `bans.xml`. IIRC the first time it happened was when 0crat was unstable for a few days. Would you kindly show me the footprint related to the affected tasks and the most recent `bans.xml`?

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1396#issuecomment-420251740))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1396](https://github.com/zerocracy/farm/issues/1396), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#1396](https://github.com/zerocracy/farm/issues/1396) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2620549969); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.33.1`

**Comment by g4s8** [comment]
@carlosmiranda it should be fixed in `0.33.1` version, can we close?

**Comment by carlosmiranda** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1396](https://github.com/zerocracy/farm/issues/1396) is now out of scope

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#1763](https://github.com/zerocracy/farm/issues/1763) is still not solved.

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#unknown]() is still not solved.
