### ISSUE TITLE
0crat can assign closed issue

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#557]
Looks like 0crat didn't remove a job from WBS after closing and assigns a performer to this issue:
https://github.com/zerocracy/farm/issues/384#issuecomment-365507099

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 well, the bug manifests itself like this:

  * The ticket gets closed;
  * GitHub sends us the webhook;
  * `RbOnClose` creates two claims: `Close job` and `Remove job from WBS`;
  * For some reason (no matter which one) the `Remove job from WBS` fails;
  * The job remains in the WBS, the order is closed;
  * Zerocrat assigns the job again.

The only solution to this problem we have now is the `remove_stale_github_ticket_from_wbs.groovy` stakeholder. The problem with this particular ticket you are referring to is that this stakeholder was broken yesterday. I fixed it just 20 hours ago: a5c7494e7674dd73e26f544ae4b450969ea65f6c

But the problem still remains. I'm thinking what can be done...

**Comment by 0crat** [comment]
Job [#557](https://github.com/zerocracy/farm/issues/557) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3925](https://www.0crat.com/u/g4s8)

**Comment by amihaiemil** [comment]
@g4s8 @yegor256 The problem is still there, see [here](https://github.com/yegor256/cactoos/pull/694). Author made a PR, closes it, then PR is put in scope and assigned for Review

**Comment by g4s8** [comment]
@yegor256 could you please post claims from footprint for this job? https://github.com/yegor256/cactoos/pull/694

**Comment by yegor256** [comment]
@g4s8 here:
<img width="933" alt="screen shot 2018-02-21 at 6 41 58 pm" src="https://user-images.githubusercontent.com/526301/36489369-efcf8cb8-1736-11e8-95c0-7ec87ef92266.png">

**Comment by amihaiemil** [comment]
@g4s8 FYI, 0crat reassigned a closed PR to me (the QA just gave the verdict, payments were made, then it reassigned it to me): https://github.com/yegor256/jpeek/pull/197#issuecomment-367666866

**Comment by amihaiemil** [comment]
@g4s8 Same situation as above here: https://github.com/yegor256/jpeek/pull/208#issuecomment-367950153

**Comment by proshin-roman** [comment]
@yegor256 @g4s8 I faced with this problem 11 hours ago in issue https://github.com/yegor256/cactoos/issues/666  - it is already closed but was assigned to me.

**Comment by yegor256** [comment]
@g4s8 I belive it's fixed already, `RbOnClose` sends only one claim now

**Comment by 0crat** [comment]
The job [#557](https://github.com/zerocracy/farm/issues/557) is now out of scope
