### ISSUE TITLE
0crat doesn't succeed paying via ethereum

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#980]
It has been a few days that 0crat tells me it can't pay me and will retry later, without success.

I am using ethereum to get paid, and I've never been paid since the beginning, so I don't know if it's new or not.

The error should be available in 0crat logs I suppose, the message I get is very succinct:
```
We tried to pay your debt of $19.62, but failed (Failed to send USD 19.62 to 0xXXXXXXXXXXXXXXXXXXXXXX via Coinbase: @victornoel/z (https://www.0crat.com/u/victornoel): Debt repayment, per §46 (http://www.zerocracy.com/policy.html#46): $3.68, $7.36, $8.58); don't worry, we will retry very soon
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@victornoel I don't see anything in the log, let's monitor more after this: 66605be

**Comment by yegor256** [comment]
@victornoel this is what we are getting in logs now:

```
Caused by: com.coinbase.api.exception.CoinbaseException: Please enter a valid email or Bitcoin address
	at com.coinbase.api.CoinbaseImpl.handleErrors(CoinbaseImpl.java:1330)
	at com.coinbase.api.CoinbaseImpl.post(CoinbaseImpl.java:1307)
	at com.coinbase.api.CoinbaseImpl.sendMoney(CoinbaseImpl.java:451)
	at com.zerocracy.pmo.banks.Crypto.pay(Crypto.java:106)
	... 71 more
```

Looks like Coinbase API doesn't understand that we are sending ETH instead of BTC.

**Comment by yegor256** [comment]
@victornoel it seems that instead of using `setAmount("USD 10")` we have to do `setAmount("ETH 0.01")`. In order to do that we have to calculate the exchange rate first.

**Comment by 0crat** [comment]
Job [#980](https://github.com/zerocracy/farm/issues/980) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6619285d-2475-4dfd-82f9-df0ae384d92c, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/elections/invalidate_all_elections.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@yegor256 reading the documentation of the API, it looks like that if you use `setAmount("ETH 0.01")` it will then be converted to BTC and sent to the address as if it is bitcoin (instead of sending to a ETH address). Are we actually sure that coinbase api support sending to ETH wallet?

**Comment by yegor256** [comment]
@victornoel do you have a link to prove that?

**Comment by victornoel** [comment]
@yegor256 yes, here they are:
In https://developers.coinbase.com/api/v1#send-money:
> The `to` field may specify a bitcoin address, email address, or Coinbase account ID

In https://developers.coinbase.com/api/v2#send-money, the `to` field is described as:
> A bitcoin address, bitcoin cash address, litecoin address, ethereum address, or an email of the recipient

In https://developers.coinbase.com/api/v2#official-client-libraries, the Java API is described as:
> Java (API v1)

**Comment by yegor256** [comment]
@victornoel it's sad... Let's wait than.

**Comment by victornoel** [comment]
@yegor256 do you mean wait for a new version of the API? Should I expect not being able to receive payment via ethereum before a long time then?

**Comment by yegor256** [comment]
@victornoel yes, you will have to wait, unfortunately. Or, we can add a new payment solution, on top of Coinbase, like cex.io, for example.

**Comment by 0crat** [comment]
The job [#980](https://github.com/zerocracy/farm/issues/980) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1611054866); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#980](https://github.com/zerocracy/farm/issues/980) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1700913092); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso I did look a bit a it, you could also implement a very simple Java API to interact with coinbase v2 (not sure it is a good idea though…)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: pool-136-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/10min/0/2/true/false by zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/10min/0/2/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): Issue: zerocracy/farm#980, Action: `created`

**Comment by paulodamaso** [comment]
@victornoel Yeah, my first thought was about implementing a API just to make these payments or decorate / extend current API, but as you said, I'm not too sure about being a good idea, any of them. @yegor256 WDYT?

**Comment by yegor256** [comment]
@paulodamaso @victornoel @g4s8 I think we should connect www.cex.io for ETH payments.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@victornoel @yegor256 @g4s8 Received a response from ceix.io:

> Dear user,
> 
> Thank you for contacting us.
> 
> API is created for automated trading based on needs of individuals and institutions. There is no withdrawal option at the moment, since there is a security requirement that each withdrawal transaction must be confirmed by account holder.
> Please also note that as per our Terms of Use: "The User represents and warrants than he/she will withdraw any cryptocurrency from his/her Account only to his/her wallets, otherwise CEX.IO does not hold any liability for the consequences of such withdrawal."
> 
> Should you require further assistance, please let us know.
> Thank you for cooperation.

Looks like we will have to think in another solution for this.

**Comment by victornoel** [comment]
@g4s8 what worries me with that is the fact that ETH, BTC and co are not stable. So either you consider that your project money is in USD or if you don't, then you have to store money in BTC/ETH/etc in this account, but it's "value" 'w.r.t. USD) can change at any time.
Furthermore, when there is not enough fund in one currency, you still need to convert your fund from one currency to the other.

Seems like a lot of problems to handle...

@paulodamaso have you looked at:
- https://github.com/yafrica/coinbase-api-v2-java
- https://bintray.com/coinbase/maven/coinbase-java (there are release of the v2 API support there)

**Comment by yegor256** [comment]
@g4s8 I like the idea about wallets, but I have a better one. What if we just pay in ZLD and find a place where users will be able to exchange ZLD to USD/BTC/ETH, etc.

**Comment by g4s8** [comment]
@yegor256 yes, it's better. But to do that, exchange system should be stable enough, so it may take some time to implement it.

**Comment by yegor256** [comment]
@g4s8 it's better to connect to an existing exchange, instead of implementing a new one. What we should do inside ZC code is to make it possible to pay ZLD and to accept project funding in ZLD.

**Comment by g4s8** [comment]
@yegor256 so I'll solve these issues to start working with Zold faster: #1119 #1120

**Comment by paulodamaso** [comment]
@victornoel Well I think we could close this one then? Should I open two new puzzles, one for making possible ZLD payments (or reference this one: https://github.com/zerocracy/farm/issues/1079 ) and another for accept project funding in ZLD?

**Comment by victornoel** [comment]
@yegor256 @g4s8 @paulodamaso I would like to remind you that the origin need was to be paid real money in ETH, not in any cryptocurrency.

@yegor256 concerning Zold: the problem is that if a project is not funded in zold, then it can't be paid in zold (or do you expect patrons to give $$ but the devs on the project are paid in zold and you (0crat) gets the $? I don't think this will happen!).

@paulodamaso concerning coinbase-java: it is common to deploy non stable versions to jcenter before it being released to maven central.

**Comment by victornoel** [comment]
@g4s8 if you consider as ARC that ETH support is not needed because we already have BTC, then let's close this.

**Comment by yegor256** [comment]
> @yegor256 concerning Zold: the problem is that if a project is not funded in zold, then it can't be paid in zold (or do you expect patrons to give $$ but the devs on the project are paid in zold and you (0crat) gets the $? I don't think this will happen!).

@victornoel  why not, if you can exchange ZLD to USD somewhere?

**Comment by victornoel** [comment]
@yegor256 I et your point; so if it is possible to convert, I agree, but it is another problem not in the cope of this issue for me: the need was ETH, not BTC nor Zold :)

**Comment by yegor256** [comment]
@victornoel yes, I realize that. But we can resolve your need (and not only yours) with just one solution: ZLD. Then, you can get whatever you want in any place you want (ETH, USD, etc) by using one of those exchanges (there thousands of them).

**Comment by paulodamaso** [comment]
@victornoel @g4s8 @yegor256 Well, trying to stick to original issue needs, I could add one puzzle for implementing ETH payments and another one for accept project funding in Zold, since I've already spent almost all my 30 min in all these researches.

**Comment by paulodamaso** [comment]
@victornoel @yegor256 @g4s8 So, what will it be? Let's close this one and left two puzzles for the new requirements that appeared in this thread (implement ETH payments with one of the two libs and allow project funding in Zold)?

**Comment by victornoel** [comment]
@paulodamaso I'm personnally waiting for @g4s8 to statute on what should happen here.

**Comment by g4s8** [comment]
@victornoel do you agree that Zold payment will solve your needs?
@yegor256 how soon we can connect Zold to exchange?

**Comment by victornoel** [comment]
@g4s8 not really. Maybe in the long term but I don't think Zold is mature enough for this.
But between eth or btc, my need was primarily to be paid in a cryptocurrency that is mature, so I'm good with no ETH support too.

**Comment by paulodamaso** [comment]
@victornoel If you are good with no ETH support, I think that this issue has no reason to stay opened, right? 

@g4s8 @yegor256  If we're assuming that we won't support ETH, we need to change the policy (https://www.zerocracy.com/policy.html#20). Alas, we need to change the policy for including ZLD payment as soon it is supported too. I can do this, but I need a definition here.

**Comment by victornoel** [comment]
@g4s8 should I close this then?

**Comment by paulodamaso** [comment]
@victornoel Policy updated, see https://github.com/zerocracy/zerocracy.github.io/pull/27 .

**Comment by victornoel** [comment]
@paulodamaso @g4s8 @yegor256 I think the bot should also stop accepting eth wallet, no?

**Comment by g4s8** [comment]
@yegor256 please say, can we drop ETH wallets support in this ticket or this bug should be fixed?

**Comment by yegor256** [comment]
@g4s8 let's just drop the support and simply inform the user that ETH can't be used, when he tries to use it.

**Comment by victornoel** [comment]
@paulodamaso see https://github.com/zerocracy/farm/issues/1298#issuecomment-401595754, I will close it after that :)

**Comment by paulodamaso** [comment]
@victornoel @g4s8 Put puzzle in code, as asked, and made a PR https://github.com/zerocracy/farm/pull/1303

**Comment by 0pdd** [comment]
@victornoel the puzzle [#1304](https://github.com/zerocracy/farm/issues/1304) is still not solved.

**Comment by victornoel** [comment]
@g4s8 @paulodamaso I'm closing this then

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#980](https://github.com/zerocracy/farm/issues/980) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@victornoel the only puzzle [#1304](https://github.com/zerocracy/farm/issues/1304) is solved here.
